### ISSUE TITLE
Fix iHeartRadio stations

### ISSUE THREAD

**Issue by paulhoule** [paulhoule/tentacruel#4]
I tried to play WICB,  it didn't work.  Fix it!

**Comment by paulhoule** [comment]
Here is the error message:

```
Task exception was never retrieved
future: <Task finished coro=<Application.play_item() done, defined at C:\Users\paul_2fb85i5\src\tentacruel\tentacruel\gui\run.py:111> exception=HeosError('Heos error 2: ID Not Valid')>
Traceback (most recent call last):
  File "C:\Users\paul_2fb85i5\src\tentacruel\tentacruel\gui\run.py", line 119, in play_item
    await self._player().add_to_queue(sid,cid,mid)
  File "C:\Users\paul_2fb85i5\src\tentacruel\tentacruel\player.py", line 183, in add_to_queue
    arguments = arguments
tentacruel.HeosError: Heos error 2: ID Not Valid
```

**Comment by paulhoule** [comment]
Ok,  now that I look at this I note that I had fixed this problem before but probably not checked in the fix.  In particular we can't add a station to the queue (a.k.a. Playlist) because (unlike a song) it doesn't have an ending.

**Comment by paulhoule** [comment]
So far so good.
